-- Year 10 ACER Level 2-style practice configuration.
insert into public.assessment_configs (
  config_key,
  year_level,
  section_counts,
  total_question_count,
  active
)
values (
  'year10_level2',
  '10',
  '{"humanities":40,"mathematics_science":32}'::jsonb,
  72,
  true
)
on conflict (config_key) do update
set
  year_level = excluded.year_level,
  section_counts = excluded.section_counts,
  total_question_count = excluded.total_question_count,
  active = excluded.active;

create table if not exists public.quiz_writing_responses (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null references public.quiz_attempts(id) on delete cascade,
  session_id uuid not null,
  task_id text not null,
  response_text text not null,
  submitted_at timestamptz not null default now(),
  unique (attempt_id, task_id)
);

alter table public.quiz_writing_responses enable row level security;
