-- Additional Year 10 question-bank content: 40 Humanities and 64 Mathematics & Science
-- questions (each page is a complete stimulus group) plus 24 Written Expression topics.
--
-- * Rows are bank rows (is_bank = true, session_id null), so the existing assessment code serves them
--   exactly like the other bank content. No application code changes are needed.
-- * Safe to re-run: a row is only inserted when its id does not already exist, so edits made in the
--   admin question-bank editor are never overwritten.
-- * answer_options is written in whichever form the column uses (jsonb, json or a text array).

drop table if exists pg_temp.new_question_bank_rows;
create temporary table new_question_bank_rows (
  id text,
  section text,
  difficulty text,
  time integer,
  question_text text,
  answer_options jsonb,
  correct_answer integer,
  explanation text,
  passage text,
  stimulus_group text
);

insert into new_question_bank_rows
  (id, section, difficulty, time, question_text, answer_options, correct_answer, explanation, passage, stimulus_group)
values
  ('HUM-BANK-N1-P01-Q1', 'humanities', 'medium', 55, 'What does Priya’s decision to put her cards down suggest?', '["She has chosen to speak honestly rather than recite.","She has forgotten what her speech was meant to say.","She hopes the audience will leave the hall early.","She is angry with the person who adjusted the microphone."]'::jsonb, 0, 'Priya replaces the rehearsed speech with something she wrote the night before, which suggests she wants to speak naturally.', 'Priya had practised the speech so often that the words no longer felt like words. In the school hall, the microphone squealed as she adjusted it, and a ripple of laughter passed through the front rows. She glanced at her notes, then at the clock above the stage, and put the cards down on the lectern. “I wrote something else last night,” she said, her voice steadier than she expected. “It’s shorter.” Someone near the back stopped whispering.', 'HUM-BANK-N1-P01'),
  ('HUM-BANK-N1-P01-Q2', 'humanities', 'hard', 60, 'Which detail best shows that the audience’s attitude is changing?', '["The microphone squealed as she adjusted it.","Someone near the back stopped whispering.","A ripple of laughter passed through the front rows.","She glanced at the clock above the stage."]'::jsonb, 1, 'The whispering stops once Priya begins to speak differently, showing the audience is starting to listen.', 'Priya had practised the speech so often that the words no longer felt like words. In the school hall, the microphone squealed as she adjusted it, and a ripple of laughter passed through the front rows. She glanced at her notes, then at the clock above the stage, and put the cards down on the lectern. “I wrote something else last night,” she said, her voice steadier than she expected. “It’s shorter.” Someone near the back stopped whispering.', 'HUM-BANK-N1-P01'),
  ('HUM-BANK-N1-P01-Q3', 'humanities', 'hard', 60, 'The phrase “the words no longer felt like words” most nearly suggests that', '["the speech had been written in another language","Priya disliked the subject she was speaking about","repeating it so often had drained it of meaning","the words were too difficult for her to pronounce"]'::jsonb, 2, 'Practising a speech until it is automatic can drain it of meaning, so the words become sounds rather than ideas.', 'Priya had practised the speech so often that the words no longer felt like words. In the school hall, the microphone squealed as she adjusted it, and a ripple of laughter passed through the front rows. She glanced at her notes, then at the clock above the stage, and put the cards down on the lectern. “I wrote something else last night,” she said, her voice steadier than she expected. “It’s shorter.” Someone near the back stopped whispering.', 'HUM-BANK-N1-P01'),
  ('HUM-BANK-N1-P01-Q4', 'humanities', 'hard', 60, 'What is the effect of the description “her voice steadier than she expected”?', '["It shows the microphone is now working properly.","It proves she is still reading closely from her notes.","It suggests the audience has stopped paying attention.","It shows her confidence growing as she takes charge."]'::jsonb, 3, 'She expected to sound nervous, but acting on her own decision steadies her.', 'Priya had practised the speech so often that the words no longer felt like words. In the school hall, the microphone squealed as she adjusted it, and a ripple of laughter passed through the front rows. She glanced at her notes, then at the clock above the stage, and put the cards down on the lectern. “I wrote something else last night,” she said, her voice steadier than she expected. “It’s shorter.” Someone near the back stopped whispering.', 'HUM-BANK-N1-P01'),
  ('HUM-BANK-N1-P01-Q5', 'humanities', 'hard', 60, 'Which word best describes the mood of the room at the end of the extract?', '["Expectant","Bored","Hostile","Careless"]'::jsonb, 0, 'The audience falls quiet and waits to hear what Priya will say next.', 'Priya had practised the speech so often that the words no longer felt like words. In the school hall, the microphone squealed as she adjusted it, and a ripple of laughter passed through the front rows. She glanced at her notes, then at the clock above the stage, and put the cards down on the lectern. “I wrote something else last night,” she said, her voice steadier than she expected. “It’s shorter.” Someone near the back stopped whispering.', 'HUM-BANK-N1-P01'),
  ('HUM-BANK-N1-P02-Q1', 'humanities', 'medium', 55, 'What is the writer’s main claim?', '["Landfill sites should be closed down across the whole region.","Leaves should be composted locally, not trucked to landfill.","Gardens no longer need soil to grow plants.","The town should plant fewer trees along its streets."]'::jsonb, 1, 'The passage argues for local composting as a better alternative to transporting leaves to landfill.', 'Every autumn, our town sweeps thousands of tonnes of fallen leaves into trucks and drives them to a landfill site forty kilometres away. This is a costly habit with a simple alternative. If leaves were collected at the park depots and composted locally, the council could return rich soil to the same gardens that lose their leaves each year. Critics say composting needs space and attracts pests, but the depot at Millbrook has operated for six years without a single recorded complaint. Surely a practice that saves money, reduces transport and rebuilds soil deserves a fair trial in every suburb.', 'HUM-BANK-N1-P02'),
  ('HUM-BANK-N1-P02-Q2', 'humanities', 'hard', 60, 'Which evidence does the writer use to answer the critics?', '["The landfill site is forty kilometres away from the town centre.","Leaves fall from the trees every autumn.","Millbrook’s depot has run for six years without complaint.","Compost can be used to make rich soil."]'::jsonb, 2, 'The Millbrook record directly answers the claim that composting depots cause problems.', 'Every autumn, our town sweeps thousands of tonnes of fallen leaves into trucks and drives them to a landfill site forty kilometres away. This is a costly habit with a simple alternative. If leaves were collected at the park depots and composted locally, the council could return rich soil to the same gardens that lose their leaves each year. Critics say composting needs space and attracts pests, but the depot at Millbrook has operated for six years without a single recorded complaint. Surely a practice that saves money, reduces transport and rebuilds soil deserves a fair trial in every suburb.', 'HUM-BANK-N1-P02'),
  ('HUM-BANK-N1-P02-Q3', 'humanities', 'hard', 60, 'The word “Surely” in the final sentence mainly serves to', '["show that the writer is unsure whether the argument works","introduce a completely new topic","report a fact taken from a council document","present the conclusion as obvious to any sensible reader"]'::jsonb, 3, '“Surely” invites agreement by treating the conclusion as common sense.', 'Every autumn, our town sweeps thousands of tonnes of fallen leaves into trucks and drives them to a landfill site forty kilometres away. This is a costly habit with a simple alternative. If leaves were collected at the park depots and composted locally, the council could return rich soil to the same gardens that lose their leaves each year. Critics say composting needs space and attracts pests, but the depot at Millbrook has operated for six years without a single recorded complaint. Surely a practice that saves money, reduces transport and rebuilds soil deserves a fair trial in every suburb.', 'HUM-BANK-N1-P02'),
  ('HUM-BANK-N1-P02-Q4', 'humanities', 'hard', 60, 'Which assumption does the argument rely on?', '["A result at one depot would carry over to other suburbs.","Composting needs no extra space or planning at all.","Critics are never correct about anything in this debate.","Leaves are the only waste the town produces."]'::jsonb, 0, 'The writer uses one successful depot to argue for a trial everywhere, which assumes the result would carry over.', 'Every autumn, our town sweeps thousands of tonnes of fallen leaves into trucks and drives them to a landfill site forty kilometres away. This is a costly habit with a simple alternative. If leaves were collected at the park depots and composted locally, the council could return rich soil to the same gardens that lose their leaves each year. Critics say composting needs space and attracts pests, but the depot at Millbrook has operated for six years without a single recorded complaint. Surely a practice that saves money, reduces transport and rebuilds soil deserves a fair trial in every suburb.', 'HUM-BANK-N1-P02'),
  ('HUM-BANK-N1-P02-Q5', 'humanities', 'hard', 60, 'Which new fact would most weaken the writer’s argument?', '["Leaves contain nutrients that plants can use.","A trial in a crowded suburb produced frequent pest problems.","The Millbrook depot is popular with visitors.","The trucks used for collection are replaced every few years."]'::jsonb, 1, 'Evidence of pest problems elsewhere would undermine the claim that depots work in every suburb.', 'Every autumn, our town sweeps thousands of tonnes of fallen leaves into trucks and drives them to a landfill site forty kilometres away. This is a costly habit with a simple alternative. If leaves were collected at the park depots and composted locally, the council could return rich soil to the same gardens that lose their leaves each year. Critics say composting needs space and attracts pests, but the depot at Millbrook has operated for six years without a single recorded complaint. Surely a practice that saves money, reduces transport and rebuilds soil deserves a fair trial in every suburb.', 'HUM-BANK-N1-P02'),
  ('HUM-BANK-N1-P03-Q1', 'humanities', 'medium', 55, 'What led to the construction of the lighthouse?', '["The government wanted to attract tourists.","Builders discovered local granite on the headland.","Several ships were wrecked on the reef.","Automatic lights became available."]'::jsonb, 2, 'The passage says the lighthouse was lit after three ships were wrecked in one winter.', 'The lighthouse at Cape Arden was first lit in 1874, after three ships were wrecked on the reef within a single winter. Its builders cut the tower from local granite, hauling each block up the headland by horse and sledge. For almost a century, keepers climbed 142 steps each evening to trim the lamp and wind the clockwork that turned the lens. When automatic lights arrived in 1969, the keepers’ cottages were abandoned. Today the tower is a museum, and visitors can see the original lens, whose glass prisms still gather a small flame’s glow into a beam that can be seen from thirty kilometres away.', 'HUM-BANK-N1-P03'),
  ('HUM-BANK-N1-P03-Q2', 'humanities', 'hard', 60, 'Which reason best explains why the cottages were abandoned in 1969?', '["The cottages were badly damaged in a severe winter storm.","The tower had been turned into a museum.","The granite blocks were reused elsewhere.","Automatic lights meant keepers were no longer needed."]'::jsonb, 3, 'The passage links the abandonment of the cottages to the arrival of automatic lights.', 'The lighthouse at Cape Arden was first lit in 1874, after three ships were wrecked on the reef within a single winter. Its builders cut the tower from local granite, hauling each block up the headland by horse and sledge. For almost a century, keepers climbed 142 steps each evening to trim the lamp and wind the clockwork that turned the lens. When automatic lights arrived in 1969, the keepers’ cottages were abandoned. Today the tower is a museum, and visitors can see the original lens, whose glass prisms still gather a small flame’s glow into a beam that can be seen from thirty kilometres away.', 'HUM-BANK-N1-P03'),
  ('HUM-BANK-N1-P03-Q3', 'humanities', 'hard', 60, 'The detail about hauling blocks “by horse and sledge” mainly shows that', '["building the tower demanded great physical effort","horses were faster than modern machinery","the builders disliked working with the local granite","the headland was flat and easy to cross"]'::jsonb, 0, 'Moving heavy stone uphill without machines required effort and persistence.', 'The lighthouse at Cape Arden was first lit in 1874, after three ships were wrecked on the reef within a single winter. Its builders cut the tower from local granite, hauling each block up the headland by horse and sledge. For almost a century, keepers climbed 142 steps each evening to trim the lamp and wind the clockwork that turned the lens. When automatic lights arrived in 1969, the keepers’ cottages were abandoned. Today the tower is a museum, and visitors can see the original lens, whose glass prisms still gather a small flame’s glow into a beam that can be seen from thirty kilometres away.', 'HUM-BANK-N1-P03'),
  ('HUM-BANK-N1-P03-Q4', 'humanities', 'hard', 60, 'Which statement is supported by the final sentence?', '["The lens was removed from the tower when it was automated.","The lens turns a small flame into a far-reaching beam.","The beam can be seen only from inside the museum.","The lens needs electricity to produce its beam."]'::jsonb, 1, 'The sentence says the prisms gather a small flame’s glow into a beam visible from thirty kilometres.', 'The lighthouse at Cape Arden was first lit in 1874, after three ships were wrecked on the reef within a single winter. Its builders cut the tower from local granite, hauling each block up the headland by horse and sledge. For almost a century, keepers climbed 142 steps each evening to trim the lamp and wind the clockwork that turned the lens. When automatic lights arrived in 1969, the keepers’ cottages were abandoned. Today the tower is a museum, and visitors can see the original lens, whose glass prisms still gather a small flame’s glow into a beam that can be seen from thirty kilometres away.', 'HUM-BANK-N1-P03'),
  ('HUM-BANK-N1-P03-Q5', 'humanities', 'hard', 60, 'What is the main purpose of the passage?', '["To persuade readers to train as lighthouse keepers today","To compare granite with other building materials","To outline the history and importance of the lighthouse","To explain how sailors navigate using clockwork"]'::jsonb, 2, 'The passage traces the lighthouse from its origin to its use as a museum.', 'The lighthouse at Cape Arden was first lit in 1874, after three ships were wrecked on the reef within a single winter. Its builders cut the tower from local granite, hauling each block up the headland by horse and sledge. For almost a century, keepers climbed 142 steps each evening to trim the lamp and wind the clockwork that turned the lens. When automatic lights arrived in 1969, the keepers’ cottages were abandoned. Today the tower is a museum, and visitors can see the original lens, whose glass prisms still gather a small flame’s glow into a beam that can be seen from thirty kilometres away.', 'HUM-BANK-N1-P03'),
  ('HUM-BANK-N1-P04-Q1', 'humanities', 'medium', 55, 'What was the total number of visitors in 2023?', '["85 thousand","105 thousand","31 thousand","95 thousand"]'::jsonb, 3, '18 + 24 + 31 + 22 = 95 thousand.', 'The Harbour Museum recorded the following visitor numbers, in thousands. In 2023: January–March 18, April–June 24, July–September 31, October–December 22. In 2024: January–March 21, April–June 27, July–September 29, October–December 35. A new maritime gallery opened in October 2024.', 'HUM-BANK-N1-P04'),
  ('HUM-BANK-N1-P04-Q2', 'humanities', 'hard', 60, 'In which quarter did visitor numbers fall from 2023 to 2024?', '["July–September","January–March","April–June","October–December"]'::jsonb, 0, 'The July–September figure fell from 31 thousand to 29 thousand. All other quarters rose.', 'The Harbour Museum recorded the following visitor numbers, in thousands. In 2023: January–March 18, April–June 24, July–September 31, October–December 22. In 2024: January–March 21, April–June 27, July–September 29, October–December 35. A new maritime gallery opened in October 2024.', 'HUM-BANK-N1-P04'),
  ('HUM-BANK-N1-P04-Q3', 'humanities', 'hard', 60, 'By how many thousand did the October–December quarter increase from 2023 to 2024?', '["7","13","10","35"]'::jsonb, 1, '35 − 22 = 13 thousand.', 'The Harbour Museum recorded the following visitor numbers, in thousands. In 2023: January–March 18, April–June 24, July–September 31, October–December 22. In 2024: January–March 21, April–June 27, July–September 29, October–December 35. A new maritime gallery opened in October 2024.', 'HUM-BANK-N1-P04'),
  ('HUM-BANK-N1-P04-Q4', 'humanities', 'hard', 60, 'Which explanation is best supported by the data?', '["The new gallery caused visitor numbers to fall in every quarter of the year.","Summer was the busiest quarter in both years.","The new gallery may have helped lift visits in the final quarter.","Visitor numbers were identical in 2023 and 2024."]'::jsonb, 2, 'The largest increase came in the quarter the gallery opened, so it may have played a part, although the data cannot prove it.', 'The Harbour Museum recorded the following visitor numbers, in thousands. In 2023: January–March 18, April–June 24, July–September 31, October–December 22. In 2024: January–March 21, April–June 27, July–September 29, October–December 35. A new maritime gallery opened in October 2024.', 'HUM-BANK-N1-P04'),
  ('HUM-BANK-N1-P04-Q5', 'humanities', 'hard', 60, 'Which statement about 2024 is correct?', '["The busiest quarter was July–September.","The quietest quarter was April–June.","Every quarter exceeded 30 thousand visitors.","The busiest quarter was October–December."]'::jsonb, 3, 'October–December had 35 thousand visitors, more than any other quarter in 2024.', 'The Harbour Museum recorded the following visitor numbers, in thousands. In 2023: January–March 18, April–June 24, July–September 31, October–December 22. In 2024: January–March 21, April–June 27, July–September 29, October–December 35. A new maritime gallery opened in October 2024.', 'HUM-BANK-N1-P04'),
  ('HUM-BANK-N1-P05-Q1', 'humanities', 'medium', 55, 'Who is the advertisement most likely aimed at?', '["People wanting a quiet break from busy city life","Astronomers who need laboratory equipment","Families looking for cinema nights and arcades","Business travellers who need reliable phone coverage"]'::jsonb, 0, 'The ad stresses leaving the city behind, with no screens or signal.', 'SLEEP UNDER REAL STARS. Leave the city glow behind. At Wren Ridge Retreat, our domed cabins have no televisions, no streetlights and no phone signal, only a sky so full of stars that you will forget your phone exists. More than 2,000 guests have returned for a second stay. Book before the end of the month and receive a free sunrise breakfast hamper.* *Offer applies to midweek stays only and cannot be combined with other discounts.', 'HUM-BANK-N1-P05'),
  ('HUM-BANK-N1-P05-Q2', 'humanities', 'hard', 60, 'Which technique is used in “a sky so full of stars that you will forget your phone exists”?', '["A statistic taken from independent research","Exaggeration to create an appealing image","A direct quotation from an expert","A warning about possible danger"]'::jsonb, 1, 'The claim is an exaggeration that makes the stargazing experience sound irresistible.', 'SLEEP UNDER REAL STARS. Leave the city glow behind. At Wren Ridge Retreat, our domed cabins have no televisions, no streetlights and no phone signal, only a sky so full of stars that you will forget your phone exists. More than 2,000 guests have returned for a second stay. Book before the end of the month and receive a free sunrise breakfast hamper.* *Offer applies to midweek stays only and cannot be combined with other discounts.', 'HUM-BANK-N1-P05'),
  ('HUM-BANK-N1-P05-Q3', 'humanities', 'hard', 60, 'What is the purpose of the information marked with an asterisk?', '["To praise the cabins even more","To list the rules guests must follow","To state limits on the offer","To thank guests who have returned"]'::jsonb, 2, 'The small print explains the conditions that apply to the free hamper.', 'SLEEP UNDER REAL STARS. Leave the city glow behind. At Wren Ridge Retreat, our domed cabins have no televisions, no streetlights and no phone signal, only a sky so full of stars that you will forget your phone exists. More than 2,000 guests have returned for a second stay. Book before the end of the month and receive a free sunrise breakfast hamper.* *Offer applies to midweek stays only and cannot be combined with other discounts.', 'HUM-BANK-N1-P05'),
  ('HUM-BANK-N1-P05-Q4', 'humanities', 'hard', 60, 'Which claim in the advertisement is supported by a figure?', '["The retreat has the clearest sky in the country.","Every cabin has a view of the sunrise.","Phones never work anywhere in the region.","Many guests have stayed more than once."]'::jsonb, 3, 'The ad gives a number, 2,000 returning guests, only for the claim about repeat stays.', 'SLEEP UNDER REAL STARS. Leave the city glow behind. At Wren Ridge Retreat, our domed cabins have no televisions, no streetlights and no phone signal, only a sky so full of stars that you will forget your phone exists. More than 2,000 guests have returned for a second stay. Book before the end of the month and receive a free sunrise breakfast hamper.* *Offer applies to midweek stays only and cannot be combined with other discounts.', 'HUM-BANK-N1-P05'),
  ('HUM-BANK-N1-P05-Q5', 'humanities', 'hard', 60, 'What is the effect of “Book before the end of the month”?', '["It creates urgency so readers decide quickly.","It explains when the stars are visible.","It announces a new type of cabin for the summer.","It warns that the retreat will then close."]'::jsonb, 0, 'A deadline pushes readers to act soon rather than delay.', 'SLEEP UNDER REAL STARS. Leave the city glow behind. At Wren Ridge Retreat, our domed cabins have no televisions, no streetlights and no phone signal, only a sky so full of stars that you will forget your phone exists. More than 2,000 guests have returned for a second stay. Book before the end of the month and receive a free sunrise breakfast hamper.* *Offer applies to midweek stays only and cannot be combined with other discounts.', 'HUM-BANK-N1-P05'),
  ('HUM-BANK-N1-P06-Q1', 'humanities', 'medium', 55, 'What does Theo’s reaction to Mara’s suggestion reveal?', '["He enjoys asking strangers for directions.","He is reluctant to admit that he might be lost.","He wants to leave the map behind.","He believes Mara is a better navigator than he is."]'::jsonb, 1, 'Theo insists everything is fine, which suggests he does not want to admit a mistake.', 'MARA: (not looking up from the map) We could just ask someone.
THEO: We’re fine. I know where the road splits.
MARA: That was an hour ago.
THEO: (folding his arms) The road has probably moved.
MARA: Roads don’t move, Theo.
THEO: Then it’s hiding. (A long pause. A car passes in the distance.)
MARA: I’m not saying you’re wrong. I’m saying the sun is going down.', 'HUM-BANK-N1-P06'),
  ('HUM-BANK-N1-P06-Q2', 'humanities', 'hard', 60, 'What is the effect of Theo’s remark, “The road has probably moved”?', '["It gives Mara accurate directions.","It shows he is angry at the passing car.","It uses humour to avoid admitting a mistake.","It proves that roads change position during the day."]'::jsonb, 2, 'The joke deflects attention from his error instead of facing it.', 'MARA: (not looking up from the map) We could just ask someone.
THEO: We’re fine. I know where the road splits.
MARA: That was an hour ago.
THEO: (folding his arms) The road has probably moved.
MARA: Roads don’t move, Theo.
THEO: Then it’s hiding. (A long pause. A car passes in the distance.)
MARA: I’m not saying you’re wrong. I’m saying the sun is going down.', 'HUM-BANK-N1-P06'),
  ('HUM-BANK-N1-P06-Q3', 'humanities', 'hard', 60, 'The stage direction “A long pause” most likely suggests', '["that the argument has been settled between them","that Mara has fallen asleep","that the passing car has stopped to help","tension as both characters consider what to do"]'::jsonb, 3, 'The silence follows Theo’s joke and gives the moment weight.', 'MARA: (not looking up from the map) We could just ask someone.
THEO: We’re fine. I know where the road splits.
MARA: That was an hour ago.
THEO: (folding his arms) The road has probably moved.
MARA: Roads don’t move, Theo.
THEO: Then it’s hiding. (A long pause. A car passes in the distance.)
MARA: I’m not saying you’re wrong. I’m saying the sun is going down.', 'HUM-BANK-N1-P06'),
  ('HUM-BANK-N1-P06-Q4', 'humanities', 'hard', 60, 'Which line shows Mara softening her approach?', '["“I’m not saying you’re wrong.”","“We could just ask someone.”","“That was an hour ago.”","“Roads don’t move, Theo.”"]'::jsonb, 0, 'Mara reassures Theo before raising her real worry, which is a gentler way to disagree.', 'MARA: (not looking up from the map) We could just ask someone.
THEO: We’re fine. I know where the road splits.
MARA: That was an hour ago.
THEO: (folding his arms) The road has probably moved.
MARA: Roads don’t move, Theo.
THEO: Then it’s hiding. (A long pause. A car passes in the distance.)
MARA: I’m not saying you’re wrong. I’m saying the sun is going down.', 'HUM-BANK-N1-P06'),
  ('HUM-BANK-N1-P06-Q5', 'humanities', 'hard', 60, 'What is Mara’s main concern in her final line?', '["The map she holds is badly out of date.","Time is running out before dark.","Theo has insulted her.","The road splits again soon."]'::jsonb, 1, 'She points out that the sun is going down.', 'MARA: (not looking up from the map) We could just ask someone.
THEO: We’re fine. I know where the road splits.
MARA: That was an hour ago.
THEO: (folding his arms) The road has probably moved.
MARA: Roads don’t move, Theo.
THEO: Then it’s hiding. (A long pause. A car passes in the distance.)
MARA: I’m not saying you’re wrong. I’m saying the sun is going down.', 'HUM-BANK-N1-P06'),
  ('HUM-BANK-N1-P07-Q1', 'humanities', 'medium', 55, 'According to the teacher, why has attendance fallen?', '["The teacher has closed the school for the whole season.","Parents disapprove of the Education Board.","Children are needed to work in the fields at harvest.","The pupils have no textbooks to use."]'::jsonb, 2, 'The letter says the harvest has begun and families need their children’s labour.', 'Marlow Creek, 14 March 1886. To the Education Board. I write to report that attendance at my school has fallen from thirty-one pupils in February to nineteen this week. The cause is not idleness. Harvest has begun, and every family needs the labour of its children in the fields from dawn until the light fails. I do not condemn these parents; I have seen how little the land gives them. I respectfully ask the Board to consider a shortened school year in harvest season rather than punish families already struggling. Yours faithfully, E. Hartley, Teacher.', 'HUM-BANK-N1-P07'),
  ('HUM-BANK-N1-P07-Q2', 'humanities', 'hard', 60, 'What is the teacher’s attitude towards the parents?', '["Angry and openly critical","Indifferent and uninterested in them","Amused and dismissive","Sympathetic and understanding"]'::jsonb, 3, 'The teacher says, “I do not condemn these parents,” and acknowledges their hardship.', 'Marlow Creek, 14 March 1886. To the Education Board. I write to report that attendance at my school has fallen from thirty-one pupils in February to nineteen this week. The cause is not idleness. Harvest has begun, and every family needs the labour of its children in the fields from dawn until the light fails. I do not condemn these parents; I have seen how little the land gives them. I respectfully ask the Board to consider a shortened school year in harvest season rather than punish families already struggling. Yours faithfully, E. Hartley, Teacher.', 'HUM-BANK-N1-P07'),
  ('HUM-BANK-N1-P07-Q3', 'humanities', 'hard', 60, 'What is the main purpose of the letter?', '["To ask the Board to adjust school rules at harvest time","To announce that the school will close permanently this year","To request that more pupils be enrolled","To complain about the teacher’s salary"]'::jsonb, 0, 'The teacher asks for a shortened school year in harvest season.', 'Marlow Creek, 14 March 1886. To the Education Board. I write to report that attendance at my school has fallen from thirty-one pupils in February to nineteen this week. The cause is not idleness. Harvest has begun, and every family needs the labour of its children in the fields from dawn until the light fails. I do not condemn these parents; I have seen how little the land gives them. I respectfully ask the Board to consider a shortened school year in harvest season rather than punish families already struggling. Yours faithfully, E. Hartley, Teacher.', 'HUM-BANK-N1-P07'),
  ('HUM-BANK-N1-P07-Q4', 'humanities', 'hard', 60, 'What does the phrase “how little the land gives them” suggest about the families?', '["They own very large and profitable farms.","They earn only a limited living from farming.","They are unwilling to farm their land.","They live too far from the school to attend."]'::jsonb, 1, 'The phrase implies that farming brings the families little return.', 'Marlow Creek, 14 March 1886. To the Education Board. I write to report that attendance at my school has fallen from thirty-one pupils in February to nineteen this week. The cause is not idleness. Harvest has begun, and every family needs the labour of its children in the fields from dawn until the light fails. I do not condemn these parents; I have seen how little the land gives them. I respectfully ask the Board to consider a shortened school year in harvest season rather than punish families already struggling. Yours faithfully, E. Hartley, Teacher.', 'HUM-BANK-N1-P07'),
  ('HUM-BANK-N1-P07-Q5', 'humanities', 'hard', 60, 'Which feature makes this letter useful to a historian?', '["It lists the name and age of every pupil.","It describes detailed plans for a new school building in town.","It shows how farming needs affected schooling in the 1880s.","It records the Board’s reply to the request."]'::jsonb, 2, 'The letter is first-hand evidence of the link between farm work and school attendance, although it reflects only one teacher’s view.', 'Marlow Creek, 14 March 1886. To the Education Board. I write to report that attendance at my school has fallen from thirty-one pupils in February to nineteen this week. The cause is not idleness. Harvest has begun, and every family needs the labour of its children in the fields from dawn until the light fails. I do not condemn these parents; I have seen how little the land gives them. I respectfully ask the Board to consider a shortened school year in harvest season rather than punish families already struggling. Yours faithfully, E. Hartley, Teacher.', 'HUM-BANK-N1-P07'),
  ('HUM-BANK-N1-P08-Q1', 'humanities', 'medium', 55, 'The streetlights are compared to “a slow sentence being written.” What does this suggest?', '["The lights are broken and flicker constantly.","The street is covered in messages written in chalk.","The lights flash on and off in a secret code.","The lights come on gradually, one after another."]'::jsonb, 3, 'A sentence is built word by word, just as the lights appear one at a time.', 'By the time I reached the bottom of the hill, the streetlights had flickered on one by one, like a slow sentence being written across the dusk. The bakery was closing; its window, still warm, fogged at the edges. A man swept the footpath with unhurried strokes, as though the evening were something to be tidied gently rather than hurried along. I slowed down. For the first time all day, there was nowhere I needed to be faster than the light.', 'HUM-BANK-N1-P08'),
  ('HUM-BANK-N1-P08-Q2', 'humanities', 'hard', 60, 'What does the phrase “something to be tidied gently” suggest about the man?', '["He works calmly and without rushing.","He is angry about the mess on the footpath.","He dislikes his job and wants to finish.","He is hurrying to close the shop."]'::jsonb, 0, 'Sweeping with “unhurried strokes” shows a calm, careful manner.', 'By the time I reached the bottom of the hill, the streetlights had flickered on one by one, like a slow sentence being written across the dusk. The bakery was closing; its window, still warm, fogged at the edges. A man swept the footpath with unhurried strokes, as though the evening were something to be tidied gently rather than hurried along. I slowed down. For the first time all day, there was nowhere I needed to be faster than the light.', 'HUM-BANK-N1-P08'),
  ('HUM-BANK-N1-P08-Q3', 'humanities', 'hard', 60, 'Which word best describes the narrator’s mood at the end?', '["Anxious","Peaceful","Resentful","Bewildered"]'::jsonb, 1, 'The narrator slows down and feels free of pressure.', 'By the time I reached the bottom of the hill, the streetlights had flickered on one by one, like a slow sentence being written across the dusk. The bakery was closing; its window, still warm, fogged at the edges. A man swept the footpath with unhurried strokes, as though the evening were something to be tidied gently rather than hurried along. I slowed down. For the first time all day, there was nowhere I needed to be faster than the light.', 'HUM-BANK-N1-P08'),
  ('HUM-BANK-N1-P08-Q4', 'humanities', 'hard', 60, 'What makes the narrator slow down?', '["The hill has become too steep for the narrator to climb.","The narrator is afraid of the dark.","The calm scene makes hurrying seem unnecessary.","The bakery is about to open."]'::jsonb, 2, 'The peaceful evening scene shows that there is no need to rush.', 'By the time I reached the bottom of the hill, the streetlights had flickered on one by one, like a slow sentence being written across the dusk. The bakery was closing; its window, still warm, fogged at the edges. A man swept the footpath with unhurried strokes, as though the evening were something to be tidied gently rather than hurried along. I slowed down. For the first time all day, there was nowhere I needed to be faster than the light.', 'HUM-BANK-N1-P08'),
  ('HUM-BANK-N1-P08-Q5', 'humanities', 'hard', 60, 'What is the effect of the final sentence?', '["It shows the narrator is late for an important appointment.","It proves the streetlights are moving quickly.","It introduces a new character to the story.","It contrasts a usual rush with a rare sense of ease."]'::jsonb, 3, '“For the first time all day” sets the calm of this moment against a busy day.', 'By the time I reached the bottom of the hill, the streetlights had flickered on one by one, like a slow sentence being written across the dusk. The bakery was closing; its window, still warm, fogged at the edges. A man swept the footpath with unhurried strokes, as though the evening were something to be tidied gently rather than hurried along. I slowed down. For the first time all day, there was nowhere I needed to be faster than the light.', 'HUM-BANK-N1-P08'),
  ('MS-BANK-N1-P01-Q1', 'mathematics_science', 'medium', 55, 'How many cells are expected after 2 hours (120 minutes)?', '["4,000","2,000","8,000","3,000"]'::jsonb, 0, '120 minutes is 3 doublings: 500 × 2 × 2 × 2 = 4,000.', 'A microbiologist grows bacteria in a nutrient broth. The culture begins with 500 cells and the number of cells doubles every 40 minutes while nutrients are plentiful. The microbiologist records the cell count at regular intervals.', 'MATH-BANK-N1-P01'),
  ('MS-BANK-N1-P01-Q2', 'mathematics_science', 'hard', 60, 'How many cells are expected after 4 hours (240 minutes)?', '["16,000","32,000","6,000","3,000"]'::jsonb, 1, '240 minutes is 6 doublings: 500 × 2⁶ = 32,000.', 'A microbiologist grows bacteria in a nutrient broth. The culture begins with 500 cells and the number of cells doubles every 40 minutes while nutrients are plentiful. The microbiologist records the cell count at regular intervals.', 'MATH-BANK-N1-P01'),
  ('MS-BANK-N1-P01-Q3', 'mathematics_science', 'hard', 60, 'After how many minutes will the culture first exceed 10,000 cells?', '["160","240","200","250"]'::jsonb, 2, 'After 160 minutes there are 8,000 cells, which is not enough. After 200 minutes (5 doublings) there are 16,000 cells.', 'A microbiologist grows bacteria in a nutrient broth. The culture begins with 500 cells and the number of cells doubles every 40 minutes while nutrients are plentiful. The microbiologist records the cell count at regular intervals.', 'MATH-BANK-N1-P01'),
  ('MS-BANK-N1-P02-Q1', 'mathematics_science', 'medium', 55, 'How much electricity do the panels produce on a sunny day?', '["1.2 kWh","18 kWh","10.8 kWh","16.2 kWh"]'::jsonb, 1, '15 panels × 1.2 kWh = 18 kWh.', 'A household uses 18 kWh of electricity each day. Each rooftop solar panel produces 1.2 kWh on a sunny day. The household has 15 panels. On a cloudy day each panel produces only 60% of its sunny-day output. The household also has a battery that stores 13.5 kWh.', 'MATH-BANK-N1-P02'),
  ('MS-BANK-N1-P02-Q2', 'mathematics_science', 'hard', 60, 'How much electricity do the panels produce on a cloudy day?', '["7.2 kWh","9.2 kWh","10.8 kWh","12.0 kWh"]'::jsonb, 2, '60% of 18 kWh = 10.8 kWh.', 'A household uses 18 kWh of electricity each day. Each rooftop solar panel produces 1.2 kWh on a sunny day. The household has 15 panels. On a cloudy day each panel produces only 60% of its sunny-day output. The household also has a battery that stores 13.5 kWh.', 'MATH-BANK-N1-P02'),
  ('MS-BANK-N1-P02-Q3', 'mathematics_science', 'hard', 60, 'On a cloudy day, how much electricity is the household short of its daily use?', '["10.8 kWh","8.2 kWh","6.0 kWh","7.2 kWh"]'::jsonb, 3, 'The shortfall is 18 − 10.8 = 7.2 kWh.', 'A household uses 18 kWh of electricity each day. Each rooftop solar panel produces 1.2 kWh on a sunny day. The household has 15 panels. On a cloudy day each panel produces only 60% of its sunny-day output. The household also has a battery that stores 13.5 kWh.', 'MATH-BANK-N1-P02'),
  ('MS-BANK-N1-P03-Q1', 'mathematics_science', 'medium', 55, 'Which variable is the independent variable in this investigation?', '["The period of the pendulum","The mass of the pendulum","The length of the pendulum","The starting angle"]'::jsonb, 2, 'The student deliberately changes the length and measures the period in response.', 'A student investigates how the length of a pendulum affects its period (the time for one full swing). The mass and the starting angle are kept the same. The results are: length 25 cm, period 1.0 s; length 50 cm, period 1.4 s; length 100 cm, period 2.0 s.', 'MATH-BANK-N1-P03'),
  ('MS-BANK-N1-P03-Q2', 'mathematics_science', 'hard', 60, 'The length is increased from 25 cm to 100 cm. What happens to the period?', '["It quadruples","It stays the same","It increases by 1.0 s","It doubles"]'::jsonb, 3, 'The length is multiplied by 4, but the period rises from 1.0 s to 2.0 s, which is multiplied by 2.', 'A student investigates how the length of a pendulum affects its period (the time for one full swing). The mass and the starting angle are kept the same. The results are: length 25 cm, period 1.0 s; length 50 cm, period 1.4 s; length 100 cm, period 2.0 s.', 'MATH-BANK-N1-P03'),
  ('MS-BANK-N1-P03-Q3', 'mathematics_science', 'hard', 60, 'Which conclusion is best supported by the results?', '["Period increases with length, but not in direct proportion to it","Period is directly proportional to length","Period does not depend on length","Period decreases as length increases"]'::jsonb, 0, 'If period were proportional to length, 4 times the length would give 4 times the period. It gives only 2 times.', 'A student investigates how the length of a pendulum affects its period (the time for one full swing). The mass and the starting angle are kept the same. The results are: length 25 cm, period 1.0 s; length 50 cm, period 1.4 s; length 100 cm, period 2.0 s.', 'MATH-BANK-N1-P03'),
  ('MS-BANK-N1-P04-Q1', 'mathematics_science', 'medium', 55, 'How far from the station is Train A when Train B departs?', '["120 km","160 km","40 km","80 km"]'::jsonb, 3, 'Train A has travelled for 1 hour at 80 km/h, so it is 80 km from the station.', 'Train A leaves a station at 10:00 and travels at a constant 80 km/h along a straight track. Train B leaves the same station on the same track at 11:00 and travels at a constant 120 km/h in the same direction. Neither train stops.', 'MATH-BANK-N1-P04'),
  ('MS-BANK-N1-P04-Q2', 'mathematics_science', 'hard', 60, 'At what time does Train B catch Train A?', '["13:00","12:00","12:30","14:00"]'::jsonb, 0, 'Train B gains 120 − 80 = 40 km each hour, so the 80 km gap closes in 2 hours after 11:00.', 'Train A leaves a station at 10:00 and travels at a constant 80 km/h along a straight track. Train B leaves the same station on the same track at 11:00 and travels at a constant 120 km/h in the same direction. Neither train stops.', 'MATH-BANK-N1-P04'),
  ('MS-BANK-N1-P04-Q3', 'mathematics_science', 'hard', 60, 'How far from the station are the trains when Train B catches Train A?', '["80 km","240 km","160 km","360 km"]'::jsonb, 1, 'Train B travels for 2 hours at 120 km/h: 240 km. Train A travels for 3 hours at 80 km/h: also 240 km.', 'Train A leaves a station at 10:00 and travels at a constant 80 km/h along a straight track. Train B leaves the same station on the same track at 11:00 and travels at a constant 120 km/h in the same direction. Neither train stops.', 'MATH-BANK-N1-P04'),
  ('MS-BANK-N1-P05-Q1', 'mathematics_science', 'medium', 55, 'How much does the yield increase when fertiliser rises from 0 kg to 20 kg?', '["0.9 t/ha","3.0 t/ha","0.6 t/ha","1.5 t/ha"]'::jsonb, 0, '3.0 − 2.1 = 0.9 t/ha.', 'A farmer tests four amounts of fertiliser on identical plots of wheat. The yield is measured in tonnes per hectare. With 0 kg of fertiliser the yield is 2.1 t/ha; with 20 kg it is 3 t/ha; with 40 kg it is 3.6 t/ha; and with 60 kg it is 3.7 t/ha. Every plot received the same water and sunlight.', 'MATH-BANK-N1-P05'),
  ('MS-BANK-N1-P05-Q2', 'mathematics_science', 'hard', 60, 'Which increase in fertiliser produced the smallest gain in yield?', '["From 0 kg to 20 kg","From 40 kg to 60 kg","From 20 kg to 40 kg","All increases produced the same gain"]'::jsonb, 1, 'The gains are 0.9, 0.6 and 0.1 t/ha, so the last 20 kg added only 0.1 t/ha.', 'A farmer tests four amounts of fertiliser on identical plots of wheat. The yield is measured in tonnes per hectare. With 0 kg of fertiliser the yield is 2.1 t/ha; with 20 kg it is 3 t/ha; with 40 kg it is 3.6 t/ha; and with 60 kg it is 3.7 t/ha. Every plot received the same water and sunlight.', 'MATH-BANK-N1-P05'),
  ('MS-BANK-N1-P05-Q3', 'mathematics_science', 'hard', 60, 'What is the percentage increase in yield from 0 kg to 60 kg of fertiliser (to the nearest whole number)?', '["1.6%","57%","76%","176%"]'::jsonb, 2, 'The increase is 3.7 − 2.1 = 1.6 t/ha. 1.6 ÷ 2.1 × 100 ≈ 76%.', 'A farmer tests four amounts of fertiliser on identical plots of wheat. The yield is measured in tonnes per hectare. With 0 kg of fertiliser the yield is 2.1 t/ha; with 20 kg it is 3 t/ha; with 40 kg it is 3.6 t/ha; and with 60 kg it is 3.7 t/ha. Every plot received the same water and sunlight.', 'MATH-BANK-N1-P05'),
  ('MS-BANK-N1-P06-Q1', 'mathematics_science', 'medium', 55, 'What is the probability that one token drawn at random is blue?', '["3/7","3/10","1/3","3/5"]'::jsonb, 1, 'There are 3 blue tokens out of 10, so the probability is 3/10.', 'A bag contains 10 tokens: 5 red, 3 blue and 2 green. Tokens are identical apart from colour and are mixed thoroughly before each draw.', 'MATH-BANK-N1-P06'),
  ('MS-BANK-N1-P06-Q2', 'mathematics_science', 'hard', 60, 'Two tokens are drawn without replacement. What is the probability that both are red?', '["1/4","1/5","2/9","5/18"]'::jsonb, 2, 'The first is red with probability 5/10, then 4 reds remain among 9 tokens: 5/10 × 4/9 = 20/90 = 2/9.', 'A bag contains 10 tokens: 5 red, 3 blue and 2 green. Tokens are identical apart from colour and are mixed thoroughly before each draw.', 'MATH-BANK-N1-P06'),
  ('MS-BANK-N1-P06-Q3', 'mathematics_science', 'hard', 60, 'A token is drawn, its colour is recorded and it is replaced. This is done 40 times. About how many red tokens are expected?', '["5","10","25","20"]'::jsonb, 3, 'Each draw is red with probability 1/2, so the expected number in 40 draws is 20. The actual number may differ.', 'A bag contains 10 tokens: 5 red, 3 blue and 2 green. Tokens are identical apart from colour and are mixed thoroughly before each draw.', 'MATH-BANK-N1-P06'),
  ('MS-BANK-N1-P07-Q1', 'mathematics_science', 'medium', 55, 'Two huts are 4.6 cm apart on the map. How far apart are they on the ground?', '["11.5 km","0.115 km","1.15 km","4.6 km"]'::jsonb, 2, '4.6 × 25,000 = 115,000 cm = 1,150 m = 1.15 km.', 'A walking map has a scale of 1 : 25,000. This means 1 cm on the map represents 25,000 cm (250 m) on the ground.', 'MATH-BANK-N1-P07'),
  ('MS-BANK-N1-P07-Q2', 'mathematics_science', 'hard', 60, 'A track is 3 km long. How long is it on the map?', '["7.5 cm","120 cm","1.2 cm","12 cm"]'::jsonb, 3, '3 km = 300,000 cm. 300,000 ÷ 25,000 = 12 cm.', 'A walking map has a scale of 1 : 25,000. This means 1 cm on the map represents 25,000 cm (250 m) on the ground.', 'MATH-BANK-N1-P07'),
  ('MS-BANK-N1-P07-Q3', 'mathematics_science', 'hard', 60, 'A lake covers 4 cm² on the map. What is its real area?', '["25 hectares","1 hectare","100 hectares","250 hectares"]'::jsonb, 0, '1 cm represents 250 m, so 1 cm² represents 62,500 m². 4 cm² = 250,000 m² = 25 hectares.', 'A walking map has a scale of 1 : 25,000. This means 1 cm on the map represents 25,000 cm (250 m) on the ground.', 'MATH-BANK-N1-P07'),
  ('MS-BANK-N1-P08-Q1', 'mathematics_science', 'medium', 55, 'How many moles of salt are in the original solution?', '["0.40 mol","0.16 mol","1.60 mol","0.10 mol"]'::jsonb, 3, 'Moles = concentration × volume = 0.40 mol/L × 0.25 L = 0.10 mol.', 'A chemist has 250 mL of a salt solution with a concentration of 0.40 mol/L. Concentration is the amount of dissolved salt (in moles) divided by the volume of solution (in litres). The chemist adds water to make the volume up to 1.0 L.', 'MATH-BANK-N1-P08'),
  ('MS-BANK-N1-P08-Q2', 'mathematics_science', 'hard', 60, 'What is the concentration after the water is added to reach 1.0 L?', '["0.10 mol/L","0.40 mol/L","0.25 mol/L","0.05 mol/L"]'::jsonb, 0, 'Adding water does not change the 0.10 mol of salt. 0.10 mol ÷ 1.0 L = 0.10 mol/L.', 'A chemist has 250 mL of a salt solution with a concentration of 0.40 mol/L. Concentration is the amount of dissolved salt (in moles) divided by the volume of solution (in litres). The chemist adds water to make the volume up to 1.0 L.', 'MATH-BANK-N1-P08'),
  ('MS-BANK-N1-P08-Q3', 'mathematics_science', 'hard', 60, 'What volume of the 0.40 mol/L solution is needed to make 500 mL of 0.08 mol/L solution by adding water?', '["80 mL","100 mL","250 mL","40 mL"]'::jsonb, 1, 'The final solution needs 0.08 × 0.5 = 0.04 mol. 0.04 ÷ 0.40 = 0.10 L = 100 mL.', 'A chemist has 250 mL of a salt solution with a concentration of 0.40 mol/L. Concentration is the amount of dissolved salt (in moles) divided by the volume of solution (in litres). The chemist adds water to make the volume up to 1.0 L.', 'MATH-BANK-N1-P08'),
  ('MS-BANK-N1-P09-Q1', 'mathematics_science', 'medium', 55, 'How much energy does the old heater use each day?', '["6 kWh","2 kWh","3 kWh","1.8 kWh"]'::jsonb, 0, '2.0 kW × 3 h = 6 kWh.', 'An old heater uses 2.0 kW of power and is switched on for 3 hours each day. A new, more efficient heater provides the same warmth but uses 1.2 kW. Electricity costs $0.30 per kWh, and energy used in kWh equals power in kW multiplied by time in hours. The new heater costs $216.', 'MATH-BANK-N1-P09'),
  ('MS-BANK-N1-P09-Q2', 'mathematics_science', 'hard', 60, 'What does it cost to run the old heater for one day?', '["$0.60","$1.80","$6.00","$0.72"]'::jsonb, 1, '6 kWh × $0.30 = $1.80.', 'An old heater uses 2.0 kW of power and is switched on for 3 hours each day. A new, more efficient heater provides the same warmth but uses 1.2 kW. Electricity costs $0.30 per kWh, and energy used in kWh equals power in kW multiplied by time in hours. The new heater costs $216.', 'MATH-BANK-N1-P09'),
  ('MS-BANK-N1-P09-Q3', 'mathematics_science', 'hard', 60, 'How much money does the new heater save each day?', '["$0.80","$1.08","$0.72","$0.24"]'::jsonb, 2, 'The new heater saves 0.8 kW × 3 h = 2.4 kWh, and 2.4 × $0.30 = $0.72.', 'An old heater uses 2.0 kW of power and is switched on for 3 hours each day. A new, more efficient heater provides the same warmth but uses 1.2 kW. Electricity costs $0.30 per kWh, and energy used in kWh equals power in kW multiplied by time in hours. The new heater costs $216.', 'MATH-BANK-N1-P09'),
  ('MS-BANK-N1-P09-Q4', 'mathematics_science', 'hard', 60, 'After how many days will the savings equal the purchase price of the new heater?', '["120 days","270 days","216 days","300 days"]'::jsonb, 3, '$216 ÷ $0.72 per day = 300 days.', 'An old heater uses 2.0 kW of power and is switched on for 3 hours each day. A new, more efficient heater provides the same warmth but uses 1.2 kW. Electricity costs $0.30 per kWh, and energy used in kWh equals power in kW multiplied by time in hours. The new heater costs $216.', 'MATH-BANK-N1-P09'),
  ('MS-BANK-N1-P10-Q1', 'mathematics_science', 'medium', 55, 'Two plants with the genotype Tt are crossed. What is the probability that an offspring is short?', '["1/2","1/4","3/4","0"]'::jsonb, 1, 'An offspring is short only if it receives t from both parents: 1/2 × 1/2 = 1/4.', 'In a species of pea plant, tall (T) is dominant to short (t). A tall plant can have the genotype TT or Tt, and a short plant must have the genotype tt. Each parent passes on one of its two alleles to each offspring, and each allele is equally likely to be passed on.', 'MATH-BANK-N1-P10'),
  ('MS-BANK-N1-P10-Q2', 'mathematics_science', 'hard', 60, 'The cross Tt × Tt produces 80 offspring. About how many are expected to be tall?', '["20","40","60","80"]'::jsonb, 2, '3/4 of the offspring are expected to be tall: 80 × 3/4 = 60.', 'In a species of pea plant, tall (T) is dominant to short (t). A tall plant can have the genotype TT or Tt, and a short plant must have the genotype tt. Each parent passes on one of its two alleles to each offspring, and each allele is equally likely to be passed on.', 'MATH-BANK-N1-P10'),
  ('MS-BANK-N1-P10-Q3', 'mathematics_science', 'hard', 60, 'A tall plant of unknown genotype is crossed with a short plant, and every one of 12 offspring is tall. Which conclusion is best supported?', '["The tall parent is definitely Tt","The tall parent must be tt","No conclusion is possible","The tall parent is probably TT"]'::jsonb, 3, 'A Tt parent would give about half short offspring. Twelve tall offspring in a row makes TT very likely, although it is not absolutely certain.', 'In a species of pea plant, tall (T) is dominant to short (t). A tall plant can have the genotype TT or Tt, and a short plant must have the genotype tt. Each parent passes on one of its two alleles to each offspring, and each allele is equally likely to be passed on.', 'MATH-BANK-N1-P10'),
  ('MS-BANK-N1-P10-Q4', 'mathematics_science', 'hard', 60, 'A Tt plant is crossed with a short plant and produces 200 offspring. About how many are expected to be short?', '["100","50","150","200"]'::jsonb, 0, 'Tt × tt gives Tt and tt equally often, so about half (100) are expected to be short.', 'In a species of pea plant, tall (T) is dominant to short (t). A tall plant can have the genotype TT or Tt, and a short plant must have the genotype tt. Each parent passes on one of its two alleles to each offspring, and each allele is equally likely to be passed on.', 'MATH-BANK-N1-P10'),
  ('MS-BANK-N2-P01-Q1', 'mathematics_science', 'medium', 55, 'What mass of the isotope remains after 15 days?', '["100 g","200 g","400 g","50 g"]'::jsonb, 0, '15 days is 3 half-lives: 800 → 400 → 200 → 100 g.', 'A radioactive isotope has a half-life of 5 days. This means that in every 5-day period, half of the radioactive atoms present at the start of that period decay into other elements. A laboratory begins with a 800 g sample of the isotope.', 'MATH-BANK-N2-P01'),
  ('MS-BANK-N2-P01-Q2', 'mathematics_science', 'hard', 60, 'After how many days will 50 g or less of the isotope remain?', '["15 days","20 days","25 days","10 days"]'::jsonb, 1, 'After 15 days 100 g remains, and after 20 days (4 half-lives) 50 g remains.', 'A radioactive isotope has a half-life of 5 days. This means that in every 5-day period, half of the radioactive atoms present at the start of that period decay into other elements. A laboratory begins with a 800 g sample of the isotope.', 'MATH-BANK-N2-P01'),
  ('MS-BANK-N2-P01-Q3', 'mathematics_science', 'hard', 60, 'Which statement about the decay is correct?', '["The same mass of the sample decays in each 5-day period","The sample is completely gone after 40 days","The same fraction of the remaining sample decays in each 5-day period","The decay speeds up as the sample becomes smaller"]'::jsonb, 2, 'Half of whatever is left decays each period, so the mass lost shrinks over time (400 g, then 200 g, then 100 g), and the sample never reaches exactly zero.', 'A radioactive isotope has a half-life of 5 days. This means that in every 5-day period, half of the radioactive atoms present at the start of that period decay into other elements. A laboratory begins with a 800 g sample of the isotope.', 'MATH-BANK-N2-P01'),
  ('MS-BANK-N2-P02-Q1', 'mathematics_science', 'medium', 55, 'How much fuel will the family car use on the 480 km trip?', '["64 L","36 L","3.6 L","45 L"]'::jsonb, 1, '480 ÷ 100 = 4.8 lots of 100 km, and 4.8 × 7.5 L = 36 L.', 'A family car uses 7.5 litres of fuel per 100 km. Fuel costs $2.10 per litre. The family is planning a 480 km holiday drive. A hybrid car uses 4.5 litres per 100 km.', 'MATH-BANK-N2-P02'),
  ('MS-BANK-N2-P02-Q2', 'mathematics_science', 'hard', 60, 'What will the fuel for the trip cost in the family car?', '["$7.56","$63.00","$75.60","$134.40"]'::jsonb, 2, '36 L × $2.10 per litre = $75.60.', 'A family car uses 7.5 litres of fuel per 100 km. Fuel costs $2.10 per litre. The family is planning a 480 km holiday drive. A hybrid car uses 4.5 litres per 100 km.', 'MATH-BANK-N2-P02'),
  ('MS-BANK-N2-P02-Q3', 'mathematics_science', 'hard', 60, 'How much less fuel would the hybrid car use on the same trip?', '["21.6 L","36 L","3.0 L","14.4 L"]'::jsonb, 3, 'The hybrid uses 3.0 L less per 100 km, and 4.8 × 3.0 L = 14.4 L.', 'A family car uses 7.5 litres of fuel per 100 km. Fuel costs $2.10 per litre. The family is planning a 480 km holiday drive. A hybrid car uses 4.5 litres per 100 km.', 'MATH-BANK-N2-P02'),
  ('MS-BANK-N2-P03-Q1', 'mathematics_science', 'medium', 55, 'What is the price after the 20% increase?', '["$220","$200","$240","$180"]'::jsonb, 2, '20% of $200 is $40, so the new price is $240.', 'A shop prices a jacket at $200. The price is first increased by 20%, and then the new price is reduced by 20%. A customer is trying to work out whether the two changes cancel each other out.', 'MATH-BANK-N2-P03'),
  ('MS-BANK-N2-P03-Q2', 'mathematics_science', 'hard', 60, 'What is the final price after the 20% reduction is applied to the new price?', '["$200","$180","$160","$192"]'::jsonb, 3, '20% of $240 is $48, and $240 − $48 = $192.', 'A shop prices a jacket at $200. The price is first increased by 20%, and then the new price is reduced by 20%. A customer is trying to work out whether the two changes cancel each other out.', 'MATH-BANK-N2-P03'),
  ('MS-BANK-N2-P03-Q3', 'mathematics_science', 'hard', 60, 'What is the overall percentage change from the original price?', '["4% decrease","No change","20% decrease","4% increase"]'::jsonb, 0, 'The final price is $8 below $200, which is 8 ÷ 200 = 4%. The two percentages apply to different amounts, so they do not cancel.', 'A shop prices a jacket at $200. The price is first increased by 20%, and then the new price is reduced by 20%. A customer is trying to work out whether the two changes cancel each other out.', 'MATH-BANK-N2-P03'),
  ('MS-BANK-N2-P04-Q1', 'mathematics_science', 'medium', 55, 'How many litres of blue paint are in the original 20 L mixture?', '["8 L","10 L","6 L","12 L"]'::jsonb, 3, 'Blue is 3 of every 5 parts: 3/5 × 20 L = 12 L.', 'A decorator mixes blue and white paint in the ratio 3 : 2 (blue : white) to make 20 litres of a pale colour. After mixing, the decorator decides the colour is too dark and adds 5 more litres of white paint.', 'MATH-BANK-N2-P04'),
  ('MS-BANK-N2-P04-Q2', 'mathematics_science', 'hard', 60, 'What is the ratio of blue to white paint after the extra white is added?', '["12 : 13","3 : 2","12 : 5","13 : 12"]'::jsonb, 0, 'The original mixture has 12 L blue and 8 L white. After adding 5 L of white there are 12 L of blue and 13 L of white.', 'A decorator mixes blue and white paint in the ratio 3 : 2 (blue : white) to make 20 litres of a pale colour. After mixing, the decorator decides the colour is too dark and adds 5 more litres of white paint.', 'MATH-BANK-N2-P04'),
  ('MS-BANK-N2-P04-Q3', 'mathematics_science', 'hard', 60, 'After adding the 5 L of white, how much extra blue paint must be added to restore the 3 : 2 ratio?', '["5 L","7.5 L","6.5 L","13 L"]'::jsonb, 1, 'With 13 L of white, the ratio needs 13 × 3/2 = 19.5 L of blue. There is 12 L, so 7.5 L must be added.', 'A decorator mixes blue and white paint in the ratio 3 : 2 (blue : white) to make 20 litres of a pale colour. After mixing, the decorator decides the colour is too dark and adds 5 more litres of white paint.', 'MATH-BANK-N2-P04'),
  ('MS-BANK-N2-P05-Q1', 'mathematics_science', 'medium', 55, 'By how many degrees does the temperature fall during the first 5 minutes?', '["28 °C","15 °C","90 °C","58 °C"]'::jsonb, 0, '90 − 62 = 28 °C.', 'A cup of hot water is left to cool in a room at 22 °C. Its temperature is recorded every 5 minutes: 0 min, 90 °C; 5 min, 62 °C; 10 min, 47 °C; 15 min, 38 °C; 20 min, 32 °C.', 'MATH-BANK-N2-P05'),
  ('MS-BANK-N2-P05-Q2', 'mathematics_science', 'hard', 60, 'During which 5-minute interval does the temperature fall by the smallest amount?', '["0–5 minutes","15–20 minutes","5–10 minutes","10–15 minutes"]'::jsonb, 1, 'The falls are 28, 15, 9 and 6 °C, so the smallest fall is between 15 and 20 minutes.', 'A cup of hot water is left to cool in a room at 22 °C. Its temperature is recorded every 5 minutes: 0 min, 90 °C; 5 min, 62 °C; 10 min, 47 °C; 15 min, 38 °C; 20 min, 32 °C.', 'MATH-BANK-N2-P05'),
  ('MS-BANK-N2-P05-Q3', 'mathematics_science', 'hard', 60, 'Which conclusion is best supported by the results?', '["The water cools at a constant rate","The water cools more quickly as it gets closer to room temperature","The water cools more slowly as it gets closer to room temperature","The water will eventually fall below room temperature"]'::jsonb, 2, 'The falls get smaller each interval as the temperature approaches 22 °C. Water cooling in a room does not drop below the room''s temperature.', 'A cup of hot water is left to cool in a room at 22 °C. Its temperature is recorded every 5 minutes: 0 min, 90 °C; 5 min, 62 °C; 10 min, 47 °C; 15 min, 38 °C; 20 min, 32 °C.', 'MATH-BANK-N2-P05'),
  ('MS-BANK-N2-P06-Q1', 'mathematics_science', 'medium', 55, 'What is the area of the garden?', '["18.84 m²","28.26 m²","9.42 m²","56.52 m²"]'::jsonb, 1, 'Area = π × r² = 3.14 × 3 × 3 = 28.26 m².', 'A circular garden has a radius of 3 m. A path 1 m wide is built all the way around the garden, so the outer edge of the path is also a circle. Use π = 3.14 for all calculations.', 'MATH-BANK-N2-P06'),
  ('MS-BANK-N2-P06-Q2', 'mathematics_science', 'hard', 60, 'What is the area enclosed by the outer edge of the path?', '["37.68 m²","28.26 m²","50.24 m²","12.56 m²"]'::jsonb, 2, 'The outer circle has radius 3 + 1 = 4 m, so its area is 3.14 × 4 × 4 = 50.24 m².', 'A circular garden has a radius of 3 m. A path 1 m wide is built all the way around the garden, so the outer edge of the path is also a circle. Use π = 3.14 for all calculations.', 'MATH-BANK-N2-P06'),
  ('MS-BANK-N2-P06-Q3', 'mathematics_science', 'hard', 60, 'What is the area of the path itself?', '["50.24 m²","28.26 m²","12.56 m²","21.98 m²"]'::jsonb, 3, 'Path area = 50.24 − 28.26 = 21.98 m².', 'A circular garden has a radius of 3 m. A path 1 m wide is built all the way around the garden, so the outer edge of the path is also a circle. Use π = 3.14 for all calculations.', 'MATH-BANK-N2-P06'),
  ('MS-BANK-N2-P07-Q1', 'mathematics_science', 'medium', 55, 'What is the balance after 2 years?', '["$5,400.00","$5,208.00","$5,408.00","$5,416.00"]'::jsonb, 2, 'Year 1: 5,000 × 1.04 = 5,200. Year 2: 5,200 × 1.04 = 5,408.', 'A student deposits $5,000 in a savings account that pays 4% interest per year. At the end of each year the interest is added to the balance, and the next year''s interest is calculated on the new, larger balance. The student makes no other deposits or withdrawals.', 'MATH-BANK-N2-P07'),
  ('MS-BANK-N2-P07-Q2', 'mathematics_science', 'hard', 60, 'How much interest has been earned in total after 3 years?', '["$600.00","$5,624.32","$208.00","$624.32"]'::jsonb, 3, 'The balance after 3 years is 5,408 × 1.04 = 5,624.32, so the interest earned is 624.32.', 'A student deposits $5,000 in a savings account that pays 4% interest per year. At the end of each year the interest is added to the balance, and the next year''s interest is calculated on the new, larger balance. The student makes no other deposits or withdrawals.', 'MATH-BANK-N2-P07'),
  ('MS-BANK-N2-P07-Q3', 'mathematics_science', 'hard', 60, 'How much more interest does this account earn over 3 years than simple interest of 4% on the original amount?', '["$24.32","$12.16","$48.64","$0.00"]'::jsonb, 0, 'Simple interest over 3 years is 3 × 200 = 600. The difference is 624.32 − 600 = 24.32.', 'A student deposits $5,000 in a savings account that pays 4% interest per year. At the end of each year the interest is added to the balance, and the next year''s interest is calculated on the new, larger balance. The student makes no other deposits or withdrawals.', 'MATH-BANK-N2-P07'),
  ('MS-BANK-N2-P08-Q1', 'mathematics_science', 'medium', 55, 'What is the density of the metal?', '["0.37 g/cm³","1.0 g/cm³","340 g/cm³","2.7 g/cm³"]'::jsonb, 3, '540 g ÷ 200 cm³ = 2.7 g/cm³.', 'A metal block has a mass of 540 g and a volume of 200 cm³. Density is mass divided by volume. Water has a density of 1.0 g/cm³. The block is lowered into a tank of water that has a flat base with an area of 400 cm².', 'MATH-BANK-N2-P08'),
  ('MS-BANK-N2-P08-Q2', 'mathematics_science', 'hard', 60, 'What is the mass of a 50 cm³ piece of the same metal?', '["135 g","27 g","2.7 g","540 g"]'::jsonb, 0, 'Mass = density × volume = 2.7 × 50 = 135 g.', 'A metal block has a mass of 540 g and a volume of 200 cm³. Density is mass divided by volume. Water has a density of 1.0 g/cm³. The block is lowered into a tank of water that has a flat base with an area of 400 cm².', 'MATH-BANK-N2-P08'),
  ('MS-BANK-N2-P08-Q3', 'mathematics_science', 'hard', 60, 'The block is completely submerged. By how much does the water level in the tank rise?', '["2.0 cm","0.5 cm","1.35 cm","5.0 cm"]'::jsonb, 1, 'The water rises by the block''s volume divided by the base area: 200 ÷ 400 = 0.5 cm.', 'A metal block has a mass of 540 g and a volume of 200 cm³. Density is mass divided by volume. Water has a density of 1.0 g/cm³. The block is lowered into a tank of water that has a flat base with an area of 400 cm².', 'MATH-BANK-N2-P08'),
  ('MS-BANK-N2-P09-Q1', 'mathematics_science', 'medium', 55, 'How many different 3-digit codes are possible?', '["1,000","30","100","900"]'::jsonb, 0, 'Each of the 3 positions has 10 choices: 10 × 10 × 10 = 1,000.', 'A digital lock opens with a code made of digits from 0 to 9. Unless a question says otherwise, a digit may be used more than once in a code.', 'MATH-BANK-N2-P09'),
  ('MS-BANK-N2-P09-Q2', 'mathematics_science', 'hard', 60, 'How many different 3-digit codes are possible if no digit may be repeated?', '["1,000","720","504","27"]'::jsonb, 1, 'There are 10 choices for the first digit, 9 for the second and 8 for the third: 10 × 9 × 8 = 720.', 'A digital lock opens with a code made of digits from 0 to 9. Unless a question says otherwise, a digit may be used more than once in a code.', 'MATH-BANK-N2-P09'),
  ('MS-BANK-N2-P09-Q3', 'mathematics_science', 'hard', 60, 'How many different 4-digit codes are possible if digits may be repeated?', '["40","1,000","10,000","5,040"]'::jsonb, 2, 'Each of the 4 positions has 10 choices: 10⁴ = 10,000.', 'A digital lock opens with a code made of digits from 0 to 9. Unless a question says otherwise, a digit may be used more than once in a code.', 'MATH-BANK-N2-P09'),
  ('MS-BANK-N2-P09-Q4', 'mathematics_science', 'hard', 60, 'Someone guesses a 3-digit code at random in one attempt. What is the probability that the guess is correct?', '["1/100","1/999","3/10","1/1000"]'::jsonb, 3, 'There are 1,000 possible codes and exactly one is correct, so the probability is 1/1000.', 'A digital lock opens with a code made of digits from 0 to 9. Unless a question says otherwise, a digit may be used more than once in a code.', 'MATH-BANK-N2-P09'),
  ('MS-BANK-N2-P10-Q1', 'mathematics_science', 'medium', 55, 'What is the weight of the box?', '["20 N","200 N","2 N","2,000 N"]'::jsonb, 1, 'Weight = mass × 10 N/kg = 20 × 10 = 200 N.', 'A 20 kg box is lifted onto a platform 1.5 m above the ground. A worker can either lift it straight up or slide it up a smooth ramp that is 5 m long and reaches the same platform. Take the force of gravity on each kilogram to be 10 N. Work done is force multiplied by the distance moved in the direction of the force.', 'MATH-BANK-N2-P10'),
  ('MS-BANK-N2-P10-Q2', 'mathematics_science', 'hard', 60, 'How much work is done lifting the box straight up 1.5 m?', '["200 J","30 J","300 J","3,000 J"]'::jsonb, 2, 'Work = 200 N × 1.5 m = 300 J.', 'A 20 kg box is lifted onto a platform 1.5 m above the ground. A worker can either lift it straight up or slide it up a smooth ramp that is 5 m long and reaches the same platform. Take the force of gravity on each kilogram to be 10 N. Work done is force multiplied by the distance moved in the direction of the force.', 'MATH-BANK-N2-P10'),
  ('MS-BANK-N2-P10-Q3', 'mathematics_science', 'hard', 60, 'Ignoring friction, what force is needed to push the box up the 5 m ramp?', '["300 N","40 N","15 N","60 N"]'::jsonb, 3, 'The same 300 J of work is done over 5 m, so the force is 300 ÷ 5 = 60 N.', 'A 20 kg box is lifted onto a platform 1.5 m above the ground. A worker can either lift it straight up or slide it up a smooth ramp that is 5 m long and reaches the same platform. Take the force of gravity on each kilogram to be 10 N. Work done is force multiplied by the distance moved in the direction of the force.', 'MATH-BANK-N2-P10'),
  ('MS-BANK-N2-P10-Q4', 'mathematics_science', 'hard', 60, 'Why would the force needed on a real ramp be greater than the ideal value?', '["Friction between the box and the ramp means extra work must be done","Gravity is stronger on a ramp than in the air","The box gains mass while it slides","Work is not conserved when a ramp is used"]'::jsonb, 0, 'Friction opposes the motion, so additional force is needed beyond the 60 N that would lift the box without friction.', 'A 20 kg box is lifted onto a platform 1.5 m above the ground. A worker can either lift it straight up or slide it up a smooth ramp that is 5 m long and reaches the same platform. Take the force of gravity on each kilogram to be 10 N. Work done is force multiplied by the distance moved in the direction of the force.', 'MATH-BANK-N2-P10');

do $$
declare
  options_type text;
begin
  select data_type into options_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'generated_questions'
    and column_name = 'answer_options';

  if options_type = 'jsonb' then
    insert into public.generated_questions (
      id, session_id, ip_hash, year_level, section, difficulty, time, question_text,
      answer_options, correct_answer, explanation, passage, stimulus_group, stimulus_image, is_bank
    )
    select r.id, null, md5('question-bank-content|' || r.id), '10', r.section, r.difficulty, r.time, r.question_text,
           r.answer_options, r.correct_answer, r.explanation, r.passage, r.stimulus_group, null, true
    from new_question_bank_rows r
    where not exists (select 1 from public.generated_questions e where e.id = r.id);
  elsif options_type = 'json' then
    insert into public.generated_questions (
      id, session_id, ip_hash, year_level, section, difficulty, time, question_text,
      answer_options, correct_answer, explanation, passage, stimulus_group, stimulus_image, is_bank
    )
    select r.id, null, md5('question-bank-content|' || r.id), '10', r.section, r.difficulty, r.time, r.question_text,
           r.answer_options::json, r.correct_answer, r.explanation, r.passage, r.stimulus_group, null, true
    from new_question_bank_rows r
    where not exists (select 1 from public.generated_questions e where e.id = r.id);
  elsif options_type = 'ARRAY' then
    insert into public.generated_questions (
      id, session_id, ip_hash, year_level, section, difficulty, time, question_text,
      answer_options, correct_answer, explanation, passage, stimulus_group, stimulus_image, is_bank
    )
    select r.id, null, md5('question-bank-content|' || r.id), '10', r.section, r.difficulty, r.time, r.question_text,
           array(select jsonb_array_elements_text(r.answer_options)), r.correct_answer, r.explanation, r.passage, r.stimulus_group, null, true
    from new_question_bank_rows r
    where not exists (select 1 from public.generated_questions e where e.id = r.id);
  else
    raise exception 'Unsupported answer_options column type: %', coalesce(options_type, 'column not found');
  end if;
end
$$;

drop table if exists pg_temp.new_question_bank_rows;

insert into public.writing_topics (id, task_slot, topic, active)
values
  ('WT-1-05', 1, 'The things we throw away can tell a story about the people who owned them.', true),
  ('WT-1-06', 1, 'A place can change you even if you only stay there for a short time.', true),
  ('WT-1-07', 1, 'Sometimes the quietest person in the room notices the most.', true),
  ('WT-1-08', 1, 'Not every failure is the opposite of success.', true),
  ('WT-1-09', 1, 'Two people can look at the same thing and see different truths.', true),
  ('WT-1-10', 1, 'A skill learned for one purpose can turn out to matter for another.', true),
  ('WT-1-11', 1, 'The first impression is rarely the whole picture.', true),
  ('WT-1-12', 1, 'Some memories grow clearer with time, while others fade away.', true),
  ('WT-1-13', 1, 'A journey is not always measured in distance.', true),
  ('WT-1-14', 1, 'Surprise can be a kind of teacher.', true),
  ('WT-1-15', 1, 'What we choose to keep says something about what we value.', true),
  ('WT-1-16', 1, 'Courage does not always look like courage from the outside.', true),
  ('WT-2-05', 2, 'A promise matters most when it is hard to keep.', true),
  ('WT-2-06', 2, 'Advice is easy to give and much harder to follow.', true),
  ('WT-2-07', 2, 'Silence can be a form of respect, or a way of avoiding the truth.', true),
  ('WT-2-08', 2, 'Fairness and equality are not always the same thing.', true),
  ('WT-2-09', 2, 'A tradition lasts only while people find a reason to keep it.', true),
  ('WT-2-10', 2, 'Asking a question can be braver than giving an answer.', true),
  ('WT-2-11', 2, 'Technology can bring people together and keep them apart at the same time.', true),
  ('WT-2-12', 2, 'It is sometimes necessary to bend a small rule in order to honour a larger one.', true),
  ('WT-2-13', 2, 'A good argument changes the speaker as much as the listener.', true),
  ('WT-2-14', 2, 'Time spent waiting is never entirely wasted.', true),
  ('WT-2-15', 2, 'Trust is built slowly and lost quickly.', true),
  ('WT-2-16', 2, 'The stories we are told as children shape the adults we become.', true)
on conflict (id) do nothing;